CREATE TABLE IF NOT EXISTS technician_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  complaint_id BIGINT UNSIGNED NOT NULL,
  tenant_user_id BIGINT UNSIGNED NOT NULL,
  technician_user_id BIGINT UNSIGNED NOT NULL,
  building_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'BDT',
  status ENUM('pending', 'successful', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
  payment_method VARCHAR(50) NULL,
  transaction_ref VARCHAR(120) NULL,
  failure_reason VARCHAR(500) NULL,
  paid_at TIMESTAMP NULL,
  callback_payload JSON NULL,
  validated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY technician_payments_transaction_ref_unique (transaction_ref),
  KEY technician_payments_technician_status_idx (technician_user_id, status),
  KEY technician_payments_tenant_status_idx (tenant_user_id, status),
  KEY technician_payments_building_idx (building_id),
  KEY technician_payments_complaint_idx (complaint_id),
  CONSTRAINT technician_payments_complaint_fk FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE,
  CONSTRAINT technician_payments_tenant_fk FOREIGN KEY (tenant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT technician_payments_technician_fk FOREIGN KEY (technician_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT technician_payments_building_fk FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;