CREATE TABLE IF NOT EXISTS otp_challenges (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  purpose ENUM('registration_verification', 'password_reset') NOT NULL,
  channel ENUM('email', 'sms') NOT NULL,
  destination VARCHAR(255) NOT NULL,
  challenge_token_hash VARCHAR(64) NOT NULL,
  otp_hash VARCHAR(128) NOT NULL,
  failed_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 5,
  resend_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  max_resends TINYINT UNSIGNED NOT NULL DEFAULT 3,
  resend_available_at TIMESTAMP NULL,
  expires_at TIMESTAMP NOT NULL,
  verified_at TIMESTAMP NULL,
  locked_until TIMESTAMP NULL,
  status ENUM('pending', 'verified', 'expired', 'locked', 'cancelled') NOT NULL DEFAULT 'pending',
  request_ip VARCHAR(45) NULL,
  user_agent TEXT NULL,
  meta JSON NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY otp_challenges_challenge_token_hash_unique (challenge_token_hash),
  KEY otp_challenges_user_id_purpose_status_index (user_id, purpose, status),
  KEY otp_challenges_purpose_status_expires_at_index (purpose, status, expires_at),
  KEY otp_challenges_locked_until_index (locked_until),
  CONSTRAINT otp_challenges_user_id_foreign FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;