CREATE TABLE IF NOT EXISTS tenant_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_user_id BIGINT UNSIGNED NOT NULL,
  unit_tenant_assignment_id BIGINT UNSIGNED NULL,
  billing_month DATE NOT NULL,
  due_date DATE NOT NULL,
  rent_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  utility_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('pending', 'partially_paid', 'paid', 'overdue') NOT NULL DEFAULT 'pending',
  paid_at TIMESTAMP NULL,
  payment_method VARCHAR(50) NULL,
  transaction_ref VARCHAR(120) NULL,
  notes VARCHAR(500) NULL,
  recorded_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  UNIQUE KEY tenant_payments_tenant_month_unique (tenant_user_id, billing_month),
  KEY tenant_payments_tenant_status_idx (tenant_user_id, status),
  CONSTRAINT tenant_payments_tenant_fk FOREIGN KEY (tenant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT tenant_payments_assignment_fk FOREIGN KEY (unit_tenant_assignment_id) REFERENCES unit_tenant_assignments(id) ON DELETE SET NULL,
  CONSTRAINT tenant_payments_recorded_by_fk FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;